### ISSUE TITLE
Unable to create prompt template

### ISSUE THREAD

**Issue by Nihal-1512** [microsoft/azurechat#325]
I have successfully deployed the solution but I am getting an error when trying to create a prompt template. Anyone know how to fix this? I have also noticed that when trying to create a prompt template, it is titled as persona instead of prompt template. 

![image](https://github.com/microsoft/azurechat/assets/148758671/23a8f1f2-4a23-450a-8216-dd8f491e8cf6)

**Comment by sonphnt** [comment]
Have you created **config** container in CosmosDB according to the migration guide?
And yes, there is a UI bug with title "Persona" when creating a Prompt.

**Comment by Nihal-1512** [comment]
Thanks for responding quick. The config container was automatically created when I deployed the solution and I did not do any of the additional steps in the migration guide.

Was I required to do the below?
![image](https://github.com/microsoft/azurechat/assets/148758671/4e2ada71-3bbf-4573-82e2-d2ce57bb0fb9)


There is both a config and history container created in CosmosDB already

**Comment by sonphnt** [comment]
Yes, you need to update all new variables in the App Service - Configuration.

**Comment by Nihal-1512** [comment]
Thanks for the help, I updated the variables and it is working now

**Comment by jnxjent** [comment]
Hi, I still face the problem "unable to create prompt" although the Configuration of App sevice as set below:
AZURE_COSMOSDB_DB_NAME=chat
AZURE_COSMOSDB_CONTAINER_NAME=history
AZURE_COSMOSDB_CONFIG_CONTAINER_NAME=config
I saved above setting and restart the app , but , nothing changed on AzureChat. Please advise what to do. Thanks!

**Comment by na20aak-herts** [comment]
@jnxjent I have the same issue, did you manage to fix the problem?

**Comment by lucamazzasette** [comment]
Hi, I've same issue.
I configured the Environment variable into Web APP :
AZURE_COSMOSDB_DB_NAME=chat
AZURE_COSMOSDB_CONTAINER_NAME=history
AZURE_COSMOSDB_CONFIG_CONTAINER_NAME=config
but the issue is not resolved.

Please help me!
